
from src.admin.app import run
from src.admin.appbackup import run
from src.admin.apprestore import run
from src.admin.index import run
from src.admin.options import run
from src.admin.serverinfo import run
from src.admin.config import run
from src.admin.date import run
from src.admin.e2vdom import run
from src.admin.echo import run
from src.admin.export import run
from src.admin.group_new import run
from src.admin.grp_modif_grp import run
from src.admin.grp_modif_rights_form import run
from src.admin.grp_modif_rights import run
from src.admin.grp_modif import run
from src.admin.grp_suppr import run
from src.admin.help import run
from src.admin.inithdd import run
from src.admin.install import run
from src.admin.ip import run
from src.admin.log_bug import run
from src.admin.log_server import run
from src.admin.log_users import run
from src.admin.log import run
from src.admin.menuappli import run
from src.admin.objects_add import run
from src.admin.objects_delete import run
from src.admin.objects_update import run
from src.admin.objects import run
from src.admin.reboot import run
from src.admin.scrupg import run
from src.admin.shutdown import run
from src.admin.ssh import run
from src.admin.track import run
from src.admin.uninstall import run
from src.admin.update import run
from src.admin.users_ajout import run
from src.admin.users_modif_rights_form import run
from src.admin.users_modif_rights import run
from src.admin.users_modif_user import run
from src.admin.users_modif import run
from src.admin.users_suppr import run
from src.admin.users import run
from src.admin.vfs import run
from src.admin.vfs_update import run
from src.admin.virtualhost import run
